/* Artykuly */

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (1,'Okazja','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-01-14');

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (2,'Wyprzedaż','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-02-01');

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (3,'Co nowego?','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-02-24');

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (4,'Nowa oferta','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-03-11');

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (5,'Tylko do końca miesiąca','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-03-30');

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (6,'Nowa oferta','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-04-04');

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (7,'Co nowego?','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-04-17');

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (8,'Co nowego?','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-05-10');

INSERT INTO article (article_id,title,body,date_of_publication)
VALUES (9,'Co nowego?','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet laoreet enim. Nulla eget leo nec libero dapibus faucibus. In vel orci lacus. Mauris tellus tellus, sollicitudin tempus porttitor vel, tempus nec est. Cras suscipit, elit nec viverra lobortis, tellus urna ornare sem, a volutpat velit est in metus. Duis et ultrices neque, non rhoncus lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida leo a sem aliquet, a pulvinar lorem malesuada. Pellentesque quis lorem urna. Nunc non magna est. Nunc consectetur in purus fringilla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi fermentum felis id turpis finibus elementum non in orci. Cras commodo justo eros, porttitor imperdiet lectus consequat in.','2024-05-21');

/* komentarze */

INSERT INTO articlecomment (comment_id,user_id,article_id,body,date_of_publication)
VALUES (1,1,2,'test','2024-04-01');